name: Quarterly Rule Review Reminder

on:
  schedule:
    - cron: '0 0 1 */3 *' # Every 3 months

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue to review rules and memories
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Quarterly Rule & Memory Hygiene Review',
              body: 'Please review all files in `.rules/` and `memories/` for accuracy, relevance, and completeness.'
            })
